engines:
    # ... CONFIG CONTENT ...
    phpmd:
        enabled: true
        # ... CONFIG CONTENT ...
        checks:
            Naming/ShortVariable:
                enabled: false
# ... CONFIG CONTENT ...
exclude_patterns:
    - 'config/'
    - 'bin/'
    - 'node_modules/'
    - 'public/'
    - 'var/'
    - 'tests/'
    - 'vendor/'
    - 'src/Kernel.php'
